export const SITE = Object.freeze({
  name: "SuiteOfficeLab",
  url: "https://suiteofficelab.com",
  description: "A browser-based office suite for editing, viewing, converting, compressing, printing, and signing common office and media files.",
  image: "/logo512.png",
  locale: "en_US",
});

export const SEO_ROUTES = Object.freeze([
  Object.freeze({"path":"/","title":"Free Browser Office Suite for CSV, Word, PowerPoint & PDF","h1":"SuiteOfficeLab browser office suite","description":"Edit CSV spreadsheets, Word-style documents, PowerPoint-style presentations, and PDF files directly in your browser. Access focused conversion, compression, viewing, printing, and document-signing tools without installing a desktop office suite.","keywords":"SuiteOfficeLab, browser office suite, CSV editor, Word editor, PowerPoint editor, PDF editor, office tools online","category":"home","priority":1.0,"changefreq":"weekly"}),
  Object.freeze({"path":"/archive","title":"Archive Document Search","h1":"Search Archive.org office documents","description":"Search Archive.org document collections for PDFs, Word files, PowerPoint files, spreadsheets, CSV files, EPUBs, and text documents from SuiteOfficeLab.","keywords":"Archive.org document search, PDF archive search, DOCX archive search, PowerPoint archive search, spreadsheet archive search","category":"archives","priority":0.82,"changefreq":"weekly"}),
  Object.freeze({"path":"/csv","title":"CSV Editor Online","h1":"Edit CSV files in your browser","description":"Upload, edit, search, add rows, add columns, copy CSV text, and export edited CSV files directly from the browser.","keywords":"CSV editor, browser CSV editor, online spreadsheet editor, edit CSV file, export CSV","category":"data","priority":0.94,"changefreq":"weekly"}),
  Object.freeze({"path":"/word","title":"Word and DOCX Editor Online","h1":"Edit Word-style documents in your browser","description":"Import DOCX files, type directly on a document page, use formatting controls, and export documents as HTML, TXT, or Word-compatible DOC files.","keywords":"Word editor, DOCX editor, browser document editor, online word processor, edit DOCX","category":"documents","priority":0.94,"changefreq":"weekly"}),
  Object.freeze({"path":"/powerpoint","title":"PowerPoint and PPTX Editor Online","h1":"Edit PowerPoint-style presentations online","description":"Import PPTX files, view slide thumbnails, edit slide titles and body text, manage speaker notes, and export presentations from the browser.","keywords":"PowerPoint editor, PPTX editor, browser slide editor, presentation editor, edit PPTX online","category":"documents","priority":0.94,"changefreq":"weekly"}),
  Object.freeze({"path":"/pdf","title":"PDF Editor and Viewer Online","h1":"Edit and view PDF files in your browser","description":"Import PDFs, view pages, zoom, add text, highlights, boxes, redaction blocks, notes, signatures, and export edited PDF files from the browser.","keywords":"PDF editor, browser PDF editor, edit PDF online, PDF markup, PDF annotations","category":"documents","priority":0.96,"changefreq":"weekly"}),
  Object.freeze({"path":"/office-tools","title":"Additional Office Tools","h1":"Additional browser office tools","description":"Use focused browser tools to view, convert, compress, clean, print, export, and sign office files directly from browser-based pages.","keywords":"browser office tools, view PDF online, print PDF online, print Word online, convert PDF to JPG, JPG to PDF, HEIC to JPG, MP3 to WAV, WAV to MP3, CSV converter","category":"office","priority":0.97,"changefreq":"weekly"}),
  Object.freeze({"path":"/convert-pdf","title":"Convert PDF Online","h1":"Convert PDF online","description":"Upload a PDF and convert it to DOCX, TXT, PNG page previews, JPG page images, or a browser-generated PDF copy.","keywords":"convert PDF online, PDF to DOCX, PDF to Word, PDF to text, PDF to PNG, PDF to JPG, browser PDF converter","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/convert-word","title":"Convert Word Document Online","h1":"Convert Word documents online","description":"Upload a DOCX file and convert it to PDF, HTML, plain text, or a browser-generated DOCX copy.","keywords":"convert Word document online, DOCX to PDF, DOCX to HTML, DOCX to text, browser Word converter","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/view-pdf","title":"View PDF Online","h1":"View PDF online","description":"Upload and view PDF pages in the browser with page navigation, zoom controls, and direct file handling.","keywords":"view PDF online, browser PDF viewer, PDF page preview, frontend PDF reader","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/view-word","title":"View Word Document Online","h1":"View Word documents online","description":"Upload a DOCX file and preview headings, paragraphs, lists, and tables as browser-readable HTML.","keywords":"view Word document online, DOCX viewer, browser Word viewer, preview DOCX online","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/view-powerpoint","title":"View PowerPoint Online","h1":"View PowerPoint files online","description":"Upload a PPTX file and view extracted slide text, slide numbers, and readable presentation content.","keywords":"view PowerPoint online, PPTX viewer, browser presentation viewer, view slides online","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/view-csv","title":"View CSV Online","h1":"View CSV files online","description":"Upload a CSV file and preview rows, columns, and spreadsheet-style table data directly in the browser.","keywords":"view CSV online, CSV viewer, browser CSV viewer, spreadsheet preview, CSV table viewer","category":"data","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/sign-document","title":"Sign Document Online","h1":"Sign documents online","description":"Upload a PDF, draw a signature with mouse, pen, touch, or drawing tablet input, place it on a page, and export a signed PDF.","keywords":"sign PDF online, sign document online, draw signature, browser PDF signing","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/compress-video","title":"Compress Video Online","h1":"Compress video online","description":"Upload MP4, MOV, or WEBM videos and create a smaller browser-generated MP4 for sharing or upload.","keywords":"compress video online, reduce video file size, compress MP4, compress MOV, video compressor","category":"media","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/compress-mp4","title":"Compress MP4 Online","h1":"Compress MP4 files online","description":"Upload an MP4 video and reduce its file size with browser video compression settings.","keywords":"compress MP4 online, reduce MP4 file size, MP4 compressor, smaller MP4 file","category":"media","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/compress-mov","title":"Compress MOV Online","h1":"Compress MOV files online","description":"Upload a MOV file from iPhone, Mac, QuickTime, or webcam workflows and create a smaller MP4 copy.","keywords":"compress MOV online, reduce MOV file size, QuickTime video compressor, iPhone MOV compressor","category":"media","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/compress-zip","title":"Compress ZIP File Online","h1":"Compress ZIP files online","description":"Upload a ZIP file, remove common junk files, rebuild it with DEFLATE compression, and export an optimized ZIP copy.","keywords":"compress ZIP online, reduce ZIP file size, optimize ZIP file, clean ZIP file","category":"archives","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/convert-csv","title":"Convert CSV Online","h1":"Convert CSV files online","description":"Upload CSV, TSV, or JSON data and convert it to JSON, cleaned CSV, PDF table output, or delimiter-adjusted spreadsheet data.","keywords":"convert CSV online, CSV converter, CSV to JSON, JSON to CSV, CSV to PDF, clean CSV file","category":"data","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/csv-to-json","title":"CSV to JSON Converter","h1":"Convert CSV to JSON","description":"Upload a CSV file and convert rows into structured JSON objects using the first row as field names.","keywords":"CSV to JSON, convert CSV to JSON online, spreadsheet to JSON, CSV JSON converter","category":"data","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/json-to-csv","title":"JSON to CSV Converter","h1":"Convert JSON to CSV","description":"Upload JSON arrays or objects and convert them into CSV rows that can be opened in spreadsheet software.","keywords":"JSON to CSV, convert JSON to CSV online, JSON spreadsheet converter","category":"data","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/csv-cleaner","title":"CSV Cleaner Online","h1":"Clean CSV files online","description":"Upload a CSV file, trim extra spaces, remove blank rows, normalize row widths, and export a cleaned CSV copy.","keywords":"CSV cleaner online, clean CSV file, remove blank CSV rows, trim CSV spaces","category":"data","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/remove-duplicate-csv-rows","title":"Remove Duplicate CSV Rows","h1":"Remove duplicate CSV rows","description":"Upload a CSV file, detect duplicate rows, remove repeated entries, and export a deduplicated CSV file.","keywords":"remove duplicate CSV rows, deduplicate CSV online, CSV duplicate remover","category":"data","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/csv-delimiter-converter","title":"CSV Delimiter Converter","h1":"Convert CSV delimiters","description":"Upload CSV or TSV files and export the same rows using comma, semicolon, tab, or pipe delimiters.","keywords":"CSV delimiter converter, convert CSV to TSV, comma to semicolon CSV","category":"data","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/csv-to-pdf","title":"CSV to PDF Converter","h1":"Convert CSV to PDF","description":"Upload a CSV file and export a browser-generated PDF copy with readable spreadsheet-style row data.","keywords":"CSV to PDF, convert CSV to PDF online, spreadsheet to PDF","category":"data","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/pdf-to-jpg","title":"Convert PDF to JPG Free","h1":"Convert PDF to JPG free","description":"Upload a PDF and export the current page or every page as high-quality JPG images directly in your browser.","keywords":"convert PDF to JPG free, PDF to JPG online, PDF page to image, PDF image converter","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/jpg-to-pdf","title":"Convert JPG to PDF Free","h1":"Convert JPG to PDF free","description":"Upload a JPG, JPEG, or PNG image and convert it into a browser-generated PDF file for free.","keywords":"convert JPG to PDF free, JPG to PDF online, JPEG to PDF, image to PDF converter","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/heic-to-jpg","title":"Convert HEIC to JPG Free","h1":"Convert HEIC to JPG free","description":"Upload an iPhone HEIC or HEIF image and convert it to a standard JPG image directly in your browser.","keywords":"convert HEIC to JPG free, HEIC to JPG online, iPhone photo converter, HEIF to JPG","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/fahrenheit-to-celsius","title":"Convert Fahrenheit to Celsius","h1":"Convert Fahrenheit to Celsius","description":"Convert Fahrenheit temperatures to Celsius instantly with a simple free browser calculator.","keywords":"convert Fahrenheit to Celsius, F to C calculator, temperature converter","category":"calculators","priority":0.9,"changefreq":"monthly"}),
  Object.freeze({"path":"/celsius-to-fahrenheit","title":"Convert Celsius to Fahrenheit","h1":"Convert Celsius to Fahrenheit","description":"Convert Celsius temperatures to Fahrenheit instantly with a simple free browser calculator.","keywords":"convert Celsius to Fahrenheit, C to F calculator, temperature converter","category":"calculators","priority":0.9,"changefreq":"monthly"}),
  Object.freeze({"path":"/convert-to-mp3","title":"Convert to MP3 Free","h1":"Convert audio or video to MP3 free","description":"Upload audio or video and export the sound as an MP3 file directly in your browser.","keywords":"convert to MP3 free, audio to MP3, video to MP3, browser MP3 converter","category":"media","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/mp3-to-wav","title":"Convert MP3 to WAV Free","h1":"Convert MP3 to WAV free","description":"Upload an MP3 file and convert it to a WAV file directly in your browser.","keywords":"MP3 to WAV free, convert MP3 to WAV online, browser audio converter","category":"media","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/wav-to-mp3","title":"Convert WAV to MP3 Free","h1":"Convert WAV to MP3 free","description":"Upload a WAV file and convert it to a smaller MP3 file directly in your browser.","keywords":"WAV to MP3 free, convert WAV to MP3 online, browser audio converter","category":"media","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/print-pdf","title":"Print PDF Online","h1":"Print PDF online","description":"Upload a PDF, preview the pages, and open the browser print dialog for the document.","keywords":"print PDF online, free PDF printer, browser PDF print, print PDF document","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/print-word","title":"Print Word Document Online","h1":"Print Word documents online","description":"Upload a DOCX file, preview the document as browser-readable HTML, and print it from the browser.","keywords":"print Word document online, print DOCX online, browser Word printer","category":"documents","priority":0.9,"changefreq":"weekly"}),
  Object.freeze({"path":"/convert-pdf-to-jpg","title":"Convert PDF to JPG Free","h1":"Convert PDF to JPG free","description":"Upload a PDF and export the current page or every page as high-quality JPG images directly in your browser.","keywords":"convert PDF to JPG free, PDF to JPG online, PDF page to image, PDF image converter","category":"documents","priority":0,"changefreq":"weekly","canonicalPath":"/pdf-to-jpg","index":false}),
  Object.freeze({"path":"/convert-jpg-to-pdf","title":"Convert JPG to PDF Free","h1":"Convert JPG to PDF free","description":"Upload a JPG, JPEG, or PNG image and convert it into a browser-generated PDF file for free.","keywords":"convert JPG to PDF free, JPG to PDF online, JPEG to PDF, image to PDF converter","category":"documents","priority":0,"changefreq":"weekly","canonicalPath":"/jpg-to-pdf","index":false}),
  Object.freeze({"path":"/convert-heic-to-jpg","title":"Convert HEIC to JPG Free","h1":"Convert HEIC to JPG free","description":"Upload an iPhone HEIC or HEIF image and convert it to a standard JPG image directly in your browser.","keywords":"convert HEIC to JPG free, HEIC to JPG online, iPhone photo converter, HEIF to JPG","category":"documents","priority":0,"changefreq":"weekly","canonicalPath":"/heic-to-jpg","index":false}),
]);

export const SEO_ROUTE_MAP = new Map(SEO_ROUTES.map((route) => [route.path, route]));

export function getSeoRoute(pathname = "/") {
  const clean = pathname === "/" ? "/" : `/${String(pathname).replace(/^\/+|\/+$/g, "")}`;
  return SEO_ROUTE_MAP.get(clean) || SEO_ROUTE_MAP.get("/");
}

export function getCanonicalPath(route) {
  return route?.canonicalPath || route?.path || "/";
}

export function getIndexableRoutes() {
  return SEO_ROUTES.filter((route) => route.index !== false);
}
